/* Statisk datasett for UT-inspirert side. Ingen backend, ingen API.
   Koordinater ligger klare for når kart skal kobles på senere.

   Dette er selve "databasen" — bare vanlige JS-konstanter (arrays og objekter)
   i stedet for en ekte database, siden siden ikke har noen server. Alle andre
   js-filer (app.js, turer.js, tur-detail.js osv.) leser fra disse listene og
   bygger HTML ut fra dem — ingenting her endres noensinne av koden selv.

   - AKTIVITETER: oppslagsverk fra aktivitets-nøkkel (f.eks. "fottur") til navn + ikon.
   - REGIONER: en enkel liste med regionnavn, brukt til filter-chips.
   - TURER: array av tur-objekter. Hvert objekt har blant annet:
       slug          — unikt "url-vennlig" navn, brukes i lenker som tur.html?slug=...
       aktivitet     — nøkkel som matcher AKTIVITETER
       sesong        — array, en tur kan passe flere sesonger samtidig
       koordinater   — { lat, lng }, klar for et fremtidig kart
   - HYTTER: array av hytte-objekter, samme prinsipp som TURER men med egne felter
       (senger, type, fasiliteter) i stedet for lengde/stigning/aktivitet. */

const AKTIVITETER = {
  fottur: { navn: "Fottur", ikon: "fottur" },
  skitur: { navn: "Skitur", ikon: "skitur" },
  topptur: { navn: "Topptur på ski", ikon: "topptur" },
  sykkeltur: { navn: "Sykkeltur", ikon: "sykkeltur" },
  padletur: { navn: "Padletur", ikon: "padletur" },
  hyttetur: { navn: "Hyttetur", ikon: "hyttetur" },
};

const REGIONER = [
  "Østlandet",
  "Vestlandet",
  "Sørlandet",
  "Trøndelag",
  "Nord-Norge",
  "Innlandet",
];

const TURER = [
  {
    id: 1,
    slug: "besseggen",
    tittel: "Besseggen",
    aktivitet: "fottur",
    region: "Østlandet",
    sesong: ["sommer", "høst"],
    vanskelighet: "Krevende",
    lengdeKm: 14,
    varighetTimer: 6,
    stigningM: 930,
    startpunkt: "Memurubu",
    koordinater: { lat: 61.4939, lng: 8.6136 },
    farge: "#3f6b4f",
    kort: "Norges mest kjente fjellrygg, med Gjende på den ene siden og Bessvatnet på den andre.",
    beskrivelse:
      "Besseggen er blitt selve symbolet på norsk fjellvandring. Ruten går langs den smale eggen mellom Gjende og Bessvatnet, med bratte stup ned mot begge vann. Turen krever godt fottøy, gode ben og litt hodet for høyder, men belønningen er noen av de mest fotograferte utsiktspunktene i landet.",
    tips: [
      "Ta båten fra Gjendesheim til Memurubu og gå tilbake til Gjendesheim.",
      "Unngå tåke og glatt fjell – eggen er utsatt i dårlig vær.",
      "Sesong er normalt juli–september, avhengig av snøforhold.",
    ],
  },
  {
    id: 2,
    slug: "trolltunga",
    tittel: "Trolltunga",
    aktivitet: "fottur",
    region: "Vestlandet",
    sesong: ["sommer"],
    vanskelighet: "Krevende",
    lengdeKm: 27,
    varighetTimer: 10,
    stigningM: 1100,
    startpunkt: "Skjeggedal",
    koordinater: { lat: 60.1242, lng: 6.7400 },
    farge: "#2f5d62",
    kort: "Den ikoniske steinflaket som stikker rett ut over Ringedalsvatnet, 700 meter over vannflaten.",
    beskrivelse:
      "Trolltunga er blant Norges mest fotograferte severdigheter. Turen er lang og krevende med stor høydeforskjell, og bør planlegges med god tid, godt vær og fulladet strøm på telefonen. Mange starter i mørket for å rekke returen før kvelden.",
    tips: [
      "Sett av hele dagen – normal gangtid er 8–12 timer tur-retur.",
      "Vurder shuttlebuss til Mågelitopp for å korte inn turen.",
      "Vinterforhold kan vare til langt ut i juni.",
    ],
  },
  {
    id: 3,
    slug: "galdhopiggen",
    tittel: "Galdhøpiggen",
    aktivitet: "fottur",
    region: "Innlandet",
    sesong: ["sommer"],
    vanskelighet: "Middels",
    lengdeKm: 12,
    varighetTimer: 5,
    stigningM: 1000,
    startpunkt: "Juvasshytta",
    koordinater: { lat: 61.6364, lng: 8.3125 },
    farge: "#4c7a5a",
    kort: "Norges høyeste fjell, 2469 moh, med brevandring fra Juvasshytta som vanligste rute.",
    beskrivelse:
      "Turen fra Juvasshytta krysser Styggebreen og krever bre-guide utenom sesong med oppmerket løype. Fra Spiterstulen er ruten lengre men uten bre. Uansett rute er dette en av de mest tilgjengelige høyfjellsturene i Norge for vanlig godt trente turgåere.",
    tips: [
      "Følg brevaktene i sesong – ikke gå alene over Styggebreen.",
      "Ta med solkrem og solbriller, refleksjonen fra breen er sterk.",
      "Sjekk værmelding for vind på toppen, den kan være mye kaldere enn i dalen.",
    ],
  },
  {
    id: 4,
    slug: "romsdalseggen",
    tittel: "Romsdalseggen",
    aktivitet: "fottur",
    region: "Vestlandet",
    sesong: ["sommer", "høst"],
    vanskelighet: "Krevende",
    lengdeKm: 12,
    varighetTimer: 7,
    stigningM: 1400,
    startpunkt: "Vengedalen",
    koordinater: { lat: 62.5389, lng: 7.7194 },
    farge: "#355e3b",
    kort: "Klassisk eggtur med utsikt over Romsdalen, Trollveggen og Åndalsnes.",
    beskrivelse:
      "Romsdalseggen regnes som en av Norges vakreste dagsturer, med utsikt over hele Romsdalen og Trollveggens loddrette fjellsider. Ruten går over flere kuler med bratte parti og noe klatring med hender, og er ikke egnet ved vått eller vindfullt vær.",
    tips: [
      "Kjøp billett til turbuss/shuttlebuss til startpunktet i sesong.",
      "Ikke anbefalt ved sterk vind – eggen er svært eksponert.",
      "Kombiner gjerne med besøk til Romsdalsmuseet i Åndalsnes.",
    ],
  },
  {
    id: 5,
    slug: "preikestolen",
    tittel: "Preikestolen",
    aktivitet: "fottur",
    region: "Sørlandet",
    sesong: ["sommer", "høst", "vår"],
    vanskelighet: "Middels",
    lengdeKm: 8,
    varighetTimer: 4,
    stigningM: 350,
    startpunkt: "Preikestolen fjellstue",
    koordinater: { lat: 58.9866, lng: 6.1903 },
    farge: "#6b8f3e",
    kort: "Det flate fjellplatået 604 meter rett over Lysefjorden, en av landets mest besøkte severdigheter.",
    beskrivelse:
      "Preikestolen er en relativt kort og grei fottur som passer for de fleste med normal kondisjon. Stien er godt tilrettelagt, men kan være svært glatt og bratt i enkelte partier. Om sommeren er det ofte mye folk på stien og på selve platået.",
    tips: [
      "Start tidlig for å unngå de største folkemengdene.",
      "Stien kan være islagt fra høst til langt ut i vår – bruk brodder.",
      "Det er ikke gjerder på platået, hold god avstand til kanten.",
    ],
  },
  {
    id: 6,
    slug: "hardangervidda-skitur",
    tittel: "Over Hardangervidda",
    aktivitet: "skitur",
    region: "Vestlandet",
    sesong: ["vinter", "vår"],
    vanskelighet: "Krevende",
    lengdeKm: 60,
    varighetTimer: 0,
    stigningM: 0,
    startpunkt: "Finse",
    koordinater: { lat: 60.5992, lng: 7.4970 },
    farge: "#7fa8c9",
    kort: "Flere dagers klassisk fjelltur på ski over Norges største høyfjellsplatå, fra hytte til hytte.",
    beskrivelse:
      "Hardangervidda er et av de mest populære områdene for flerdagers skiturer i Norge, med et tett nett av betjente og selvbetjente DNT-hytter. Vidda er åpen og værhardt, så gode kart- og kompassferdigheter (eller GPS) er nødvendig.",
    tips: [
      "Planlegg dagsetapper mellom hyttene og hold av en buffer-dag for uvær.",
      "Meld fra om ruteplan til noen hjemme.",
      "Vær forberedt på total hvit-ut – vidda gir få naturlige holdepunkter.",
    ],
  },
  {
    id: 7,
    slug: "gaustatoppen-topptur",
    tittel: "Gaustatoppen på ski",
    aktivitet: "topptur",
    region: "Østlandet",
    sesong: ["vinter", "vår"],
    vanskelighet: "Krevende",
    lengdeKm: 9,
    varighetTimer: 6,
    stigningM: 1100,
    startpunkt: "Stavsro",
    koordinater: { lat: 59.8497, lng: 8.6531 },
    farge: "#8ea9c9",
    kort: "Toppturklassiker i Telemark med et av landets mest kjente utsiktspunkt, synlig over en sjettedel av Norge.",
    beskrivelse:
      "Fra Stavsro følger man sommerstien opp mot toppen, med jevn stigning og fantastisk utsikt store deler av veien. Skredfare må alltid vurderes i bratte parti nær toppen, og turen bør ikke gjøres alene i dårlig sikt.",
    tips: [
      "Sjekk skredvarsel på varsom.no før du legger ut.",
      "Toppen har radiolinje-hytte – ikke offentlig tilgjengelig, kun for nødstilfeller.",
      "Beregn god tid til nedkjøring, forholdene varierer mye med høyden.",
    ],
  },
  {
    id: 8,
    slug: "lofoten-sykkel",
    tittel: "Lofoten rundt",
    aktivitet: "sykkeltur",
    region: "Nord-Norge",
    sesong: ["sommer"],
    vanskelighet: "Middels",
    lengdeKm: 220,
    varighetTimer: 0,
    stigningM: 0,
    startpunkt: "Svolvær",
    koordinater: { lat: 68.2342, lng: 14.5773 },
    farge: "#c9905a",
    kort: "Flere dagers landeveissykling gjennom dramatiske fjell, fiskevær og hvite strender.",
    beskrivelse:
      "En sykkeltur gjennom Lofoten byr på noen av Norges mest fotogene veistrekninger, med tindrende fjell rett fra havet. Ruten kan deles opp over 4–6 dager med overnatting i fiskevær og campingplasser underveis.",
    tips: [
      "Sommersesongen har mye trafikk på E10 – vurder tidlig morgen for roligere veier.",
      "Vind kan være en større utfordring enn stigning i Lofoten.",
      "Book overnatting i god tid, spesielt i juli.",
    ],
  },
  {
    id: 9,
    slug: "femund-padling",
    tittel: "Padling på Femunden",
    aktivitet: "padletur",
    region: "Innlandet",
    sesong: ["sommer"],
    vanskelighet: "Middels",
    lengdeKm: 35,
    varighetTimer: 0,
    stigningM: 0,
    startpunkt: "Elgå",
    koordinater: { lat: 62.2331, lng: 12.0136 },
    farge: "#3e7a8f",
    kort: "Rolig padling på Norges tredje største innsjø, omgitt av villmark og Femundsmarka nasjonalpark.",
    beskrivelse:
      "Femunden byr på flere dagers padletur med muligheter for teltovernatting langs bredden eller overnatting på DNT-hytter i Femundsmarka. Innsjøen kan bli hard ved vind, så følg med på værvarsel og hold deg nær land ved tvil.",
    tips: [
      "Kajakk eller kano kan leies i Elgå og Drevsjø.",
      "Sett av ekstra dager som værbuffer – Femunden tåler ikke sterk vind.",
      "Fiskekort kan kjøpes lokalt for de som vil fiske underveis.",
    ],
  },
  {
    id: 10,
    slug: "rondane-hyttetur",
    tittel: "Hytte-til-hytte i Rondane",
    aktivitet: "hyttetur",
    region: "Innlandet",
    sesong: ["sommer", "høst", "vinter"],
    vanskelighet: "Middels",
    lengdeKm: 45,
    varighetTimer: 0,
    stigningM: 0,
    startpunkt: "Mysusæter",
    koordinater: { lat: 61.5539, lng: 9.6900 },
    farge: "#8a6b4c",
    kort: "Flere dagers rundtur mellom DNT-hytter i Rondane nasjonalpark, Norges eldste nasjonalpark.",
    beskrivelse:
      "Rondane egner seg godt for en flerdagerstur mellom betjente og selvbetjente hytter, med varierte turer fra rolige dalturer til bestigning av Rondeslottet og Storronden. Området er kjent for gode stier og relativt bart landskap som gir god oversikt.",
    tips: [
      "Bestill overnatting på betjente hytter i sesong.",
      "Ta med nøkkelkort for selvbetjente DNT-hytter.",
      "Villreinen i Rondane er sky – hold avstand og følg oppsatte stier i kalvingsperioden.",
    ],
  },
  {
    id: 11,
    slug: "kjeragbolten",
    tittel: "Kjeragbolten",
    aktivitet: "fottur",
    region: "Sørlandet",
    sesong: ["sommer"],
    vanskelighet: "Krevende",
    lengdeKm: 11,
    varighetTimer: 6,
    stigningM: 800,
    startpunkt: "Øygardsstøl",
    koordinater: { lat: 59.0339, lng: 6.7311 },
    farge: "#4c7a5a",
    kort: "Steinblokken klemt fast i en fjellsprekk 1000 meter over Lysefjorden – for de med godt hode for høyder.",
    beskrivelse:
      "Turen til Kjerag går over flere bratte fjellparti med kjettinger til hjelp i de mest utsatte partiene. Selve steinen krever ikke klatring, men mange velger å bare beundre den fra siden. Total høydeforskjell opp og ned er betydelig større enn avstanden skulle tilsi.",
    tips: [
      "Bruk kjettingene aktivt i de bratteste partiene, spesielt i vått vær.",
      "Turen tar lenger tid enn mange tror – sett av hele dagen.",
      "Ikke anbefalt for de med høydeskrekk.",
    ],
  },
  {
    id: 12,
    slug: "oksskolten-topptur",
    tittel: "Øksskolten på ski",
    aktivitet: "topptur",
    region: "Nord-Norge",
    sesong: ["vinter", "vår"],
    vanskelighet: "Krevende",
    lengdeKm: 16,
    varighetTimer: 8,
    stigningM: 1200,
    startpunkt: "Okstindan",
    koordinater: { lat: 66.0122, lng: 14.3050 },
    farge: "#8ea9c9",
    kort: "Nordlands høyeste fjell, en alpin topptur i storslått breterreng i Okstindan.",
    beskrivelse:
      "Øksskolten byr på krevende, bretrukket terreng og er en tur for erfarne skiturfolk med bre-erfaring. Ruten går gjennom dramatisk høyfjell med isbreer og krever gode is- og skredferdigheter.",
    tips: [
      "Bre-erfaring og riktig utstyr (isøks, stegjern) er nødvendig.",
      "Bruk lokalkjent guide om du ikke kjenner området.",
      "Sjekk skredvarsel grundig – terrenget er alpint mange steder.",
    ],
  },
  {
    id: 13,
    slug: "trondheim-bymarka-sykkel",
    tittel: "Bymarka rundt",
    aktivitet: "sykkeltur",
    region: "Trøndelag",
    sesong: ["sommer", "høst", "vår"],
    vanskelighet: "Enkel",
    lengdeKm: 25,
    varighetTimer: 3,
    stigningM: 400,
    startpunkt: "Lian",
    koordinater: { lat: 63.4098, lng: 10.2864 },
    farge: "#c9905a",
    kort: "Populær rundtur på grusveier og stier gjennom Trondheims bynære turterreng.",
    beskrivelse:
      "Bymarka er lett tilgjengelig med trikk fra Trondheim sentrum og byr på et godt utbygd nett av grusveier som passer for de fleste sykkeltyper. Turen passerer flere vann og gir en fin blanding av skog og åpne partier.",
    tips: [
      "Ta trikken til Lian for en enkel start uten bilkjøring.",
      "Flere serveringssteder underveis i sommersesongen.",
      "Fint alternativ også for terrengsykkel med barn i følge.",
    ],
  },
  {
    id: 14,
    slug: "trollstigen-skitur",
    tittel: "Skitur til Bispen",
    aktivitet: "skitur",
    region: "Vestlandet",
    sesong: ["vinter", "vår"],
    vanskelighet: "Middels",
    lengdeKm: 10,
    varighetTimer: 5,
    stigningM: 900,
    startpunkt: "Trollstigen",
    koordinater: { lat: 62.4531, lng: 7.6864 },
    farge: "#7fa8c9",
    kort: "Fin topptur i Romsdalsalpene med utsikt mot Trollstigen og Reinheimen.",
    beskrivelse:
      "En fin og variert topptur som passer godt tidlig vår når snøen har satt seg. Turen gir flott utsikt over de dramatiske fjellformasjonene i Romsdalsalpene og en fin nedkjøring i godt skiføre.",
    tips: [
      "Vurder skredfare nøye – bratte parti i øvre del av turen.",
      "Trollstigen fylkesvei er stengt om vinteren, sjekk adkomst.",
      "Best forhold er ofte i mars–april.",
    ],
  },
];

const HYTTER = [
  {
    id: 1,
    slug: "gjendesheim",
    navn: "Gjendesheim",
    region: "Østlandet",
    type: "Betjent",
    senger: 200,
    koordinater: { lat: 61.4708, lng: 8.7100 },
    farge: "#3f6b4f",
    kort: "Startpunkt for Besseggen, med full servering og god standard midt i Jotunheimen.",
    beskrivelse:
      "Gjendesheim ligger idyllisk til ved enden av Gjende og er utgangspunkt for flere av Jotunheimens mest kjente turer, deriblant Besseggen. Hytta har full servering i sesong og er et naturlig knutepunkt for turfolk.",
    fasiliteter: ["Servering", "Dusj", "Bagasjeoppbevaring", "Butikk"],
  },
  {
    id: 2,
    slug: "fondsbu",
    navn: "Fondsbu",
    region: "Østlandet",
    type: "Betjent",
    senger: 100,
    koordinater: { lat: 61.3944, lng: 8.4297 },
    farge: "#4c7a5a",
    kort: "Vakkert plassert ved Bygdin, populært utgangspunkt for turer i Jotunheimen.",
    beskrivelse:
      "Fondsbu ligger på nordsiden av Bygdin og er kjent for sin flotte beliggenhet med utsikt over vannet og fjellene rundt. Hytta er godt besøkt sommerstid og er et fint stopp på lengre rundturer i Jotunheimen.",
    fasiliteter: ["Servering", "Dusj", "Tørkerom"],
  },
  {
    id: 3,
    slug: "finse-1222",
    navn: "Finse 1222",
    region: "Vestlandet",
    type: "Betjent",
    senger: 175,
    koordinater: { lat: 60.6011, lng: 7.4964 },
    farge: "#7fa8c9",
    kort: "Høyfjellshotell og DNT-hytte ved Finse stasjon, portal til Hardangervidda.",
    beskrivelse:
      "Finse er kjent som et av de mest værharde og spektakulære utgangspunktene for fjellturer i Norge, med togforbindelse rett til døra. Herfra kan man gå videre inn på Hardangervidda eller til Hardangerjøkulen.",
    fasiliteter: ["Servering", "Dusj", "Ski- og sykkelutleie", "Butikk"],
  },
  {
    id: 4,
    slug: "rondvassbu",
    navn: "Rondvassbu",
    region: "Innlandet",
    type: "Betjent",
    senger: 124,
    koordinater: { lat: 61.5983, lng: 9.7719 },
    farge: "#8a6b4c",
    kort: "Klassisk fjellstue i hjertet av Rondane, nær flere av parkens kjente topper.",
    beskrivelse:
      "Rondvassbu ligger vakkert til ved Rondvatnet og er utgangspunkt for turer til blant annet Storronden og Vinjeronden. Hytta har lang tradisjon og er et populært stopp for både dagsturer og lengre rundturer.",
    fasiliteter: ["Servering", "Dusj", "Badstue"],
  },
  {
    id: 5,
    slug: "letterhytta",
    navn: "Letterhytta",
    region: "Vestlandet",
    type: "Selvbetjent",
    senger: 16,
    koordinater: { lat: 60.2419, lng: 6.8814 },
    farge: "#2f5d62",
    kort: "Enkel selvbetjent hytte for turer i nærheten av Trolltunga og Hardangervidda.",
    beskrivelse:
      "En koselig og enkel selvbetjent hytte som passer godt som overnatting på lengre turer i området. Krever DNT-nøkkelkort, og turgåere må selv ta med eller kjøpe niste fra hyttas matbod.",
    fasiliteter: ["Vedovn", "Matbod", "Utedo"],
  },
  {
    id: 6,
    slug: "tarjebu",
    navn: "Tarjebu",
    region: "Sørlandet",
    type: "Ubetjent",
    senger: 8,
    koordinater: { lat: 59.3628, lng: 7.4622 },
    farge: "#6b8f3e",
    kort: "Liten, enkel og gratis ubetjent hytte i Setesdalsheiene.",
    beskrivelse:
      "Tarjebu er en typisk ubetjent DNT-hytte uten mat eller vaktmester – kun tak over hodet, ved og enkle senger. Passer godt for de som ønsker en enkel og rimelig overnatting langt fra folk.",
    fasiliteter: ["Vedovn", "Utedo"],
  },
  {
    id: 7,
    slug: "kjelvatnet",
    navn: "Kjelvatnet",
    region: "Nord-Norge",
    type: "Selvbetjent",
    senger: 12,
    koordinater: { lat: 66.1206, lng: 14.2011 },
    farge: "#8ea9c9",
    kort: "Selvbetjent hytte i Okstindan, populær base for brevandring og toppturer.",
    beskrivelse:
      "Kjelvatnet ligger med utsikt mot Okstindbreen og er et naturlig utgangspunkt for turer i det alpine Okstindan-området. Krever noe erfaring med bre- og fjellterreng for videre turer herfra.",
    fasiliteter: ["Vedovn", "Matbod", "Utedo"],
  },
  {
    id: 8,
    slug: "vessingsjohytta",
    navn: "Vessingsjøhytta",
    region: "Innlandet",
    type: "Ubetjent",
    senger: 10,
    koordinater: { lat: 61.7331, lng: 9.4658 },
    farge: "#4c7a5a",
    kort: "Rolig ubetjent hytte i Rondane nord, langt fra de mest trafikkerte stiene.",
    beskrivelse:
      "En stille og lite besøkt hytte som gir god følelse av villmark, med muligheter for gode fiskevann i nærheten. Et fint valg for de som ønsker ro og lite folk på turen.",
    fasiliteter: ["Vedovn", "Utedo"],
  },
];
