POST http://localhost:3030/varer HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "VNr":"99997",
    "Betegnelse":"Dukkehår, hvitt",
    "Pris":"55.50",
    "KatNr":"13",
    "Antall":"106",
    "Hylle":"E12",
    "Slettet":"0",
    "Bildefil":"steve-johnson-B2_zWEdpLlo-unsplash.jpg"
}